{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rhinoscriptsyntax as rs \n",
    "import Rhino. Geometry as rg \n",
    "import System.Drawing as sd\n",
    "from Grasshopper.Kernel \n",
    "import GH _RuntimeMessageLevel as rmi \n",
    "import ghpythonlib.components as ghc\n",
    "\n",
    "# length of lines\n",
    "linex = 0.866*line\n",
    "liney = 0.5*line\n",
    "\n",
    "# space between patterns\n",
    "Yjump = line + space\n",
    "Xjump = 1.732*line + 2*space\n",
    "\n",
    "# define data structures\n",
    "patterns = []\n",
    "lines = []\n",
    "temp_pattern = []\n",
    "offset_lines = []\n",
    "\n",
    "# create first pattern (higher column)\n",
    "for x in range(Xcount) :\n",
    "    for y in range(Ycount):\n",
    "\n",
    "        # create center point\n",
    "        ptX = x*Xjump\n",
    "        pty = y*Yjump\n",
    "        ptCenter = rg.Point3d(ptx, pty,0)\n",
    "\n",
    "        # create edge points\n",
    "        ptW1 = rg-Point3d(ptX, ptY + line, 0)\n",
    "        ptw2 = rg.Point3d(ptX - linex, pty - liney,0)\n",
    "        ptW3 = rg. Point3d(ptX + linex, pty - liney, 0)\n",
    "\n",
    "        # create lines\n",
    "        linel = rg-Polyline([ptCenter, ptw1, ptCenter])\n",
    "        line2 = rg-Polyline([ptCenter, ptw2, ptCenter])\n",
    "        line3 = rg.Polyline([ptCenter, ptW3, ptCenter])\n",
    "\n",
    "        # create curve\n",
    "        lines.append(line1.ToNurbsCurve())\n",
    "        lines.append(line2. ToNurbsCurve())\n",
    "        lines.append(line3. ToNurbsCurve())\n",
    "\n",
    "        # merge all curves to one array\n",
    "        temp_pattern.append(linel. ToNurbsCurve())\n",
    "        temp_pattern.append(line2. ToNurbsCurve()) \n",
    "        temp_pattern.append(line3.ToNurbsCurve())\n",
    "        patterns.append(temp_pattern)\n",
    "        temp_pattern = []\n",
    "\n",
    "# create second pattern (lower column)\n",
    "for x in range(Xcount):\n",
    "    for y in range(Ycount):\n",
    "\n",
    "        # create center point\n",
    "        ptX = x*Xjump + linex + space\n",
    "        ptY = y*Yjump - 0.58*line\n",
    "        ptCenter = rg.Point3d(ptX,ptY,0)\n",
    "\n",
    "        # create edge point\n",
    "        ptW1 = rg.Point3d(ptX, ptY + line, 0)\n",
    "        ptW2 = rg-Point3d(ptX - linex, ptY - liney, 0)\n",
    "        ptW3 = rg.Point3d(ptX + linex, pty - liney, 0)\n",
    "\n",
    "        # create lines\n",
    "        line1 = rg.Polyline([ptCenter, ptw1, ptCenter])\n",
    "        line2 = rg-Polyline([ptCenter, ptW2, ptCenter])\n",
    "        line3 = rg. Polyline([ptCenter, ptW3, ptCenter])\n",
    "\n",
    "        # ceate curves\n",
    "        lines.append(line1.ToNurbsCurve())\n",
    "        lines.append (line2. ToNurbsCurve())\n",
    "        lines.append(line3.ToNurbsCurve())\n",
    "\n",
    "        # merge all curves to one array\n",
    "        temp_pattern.append(linel.ToNurbsCurve())\n",
    "        temp_pattern.append(line2.ToNurbsCurve())\n",
    "        temp_pattern,append(line3. ToNurbsCurve())\n",
    "        patterns. append (temp_pattern)\n",
    "        temp_pattern = []\n",
    "\n",
    "# create a rectangle around the pattern\n",
    "plane = rg. Plane(rg-Point3d(-(2*linex),-(4*liney),0,0), rg.Vector3d(1,0,0), rg.Vector3d(0,1,0))\n",
    "width = ptX + 4*linex\n",
    "height = pty + 9*liney\n",
    "rectangle = rg.Rectangle3d(plane, width, height)\n",
    "    \n",
    "# create an offset to the pattern\n",
    "for x in lines: #patterns\n",
    "offset_line = x.Offset(rg-Plane.WorldY, dis_crv, 0.001, rg.Curve0ffsetCornerStyle.Sharp)\n",
    "    if offset_line:\n",
    "        offset_lines.append(offset_line[e])\n",
    "\n",
    "# create a surface from the pattern\n",
    "boundary_lines = rs.AddPlanarSrf(offset_lines)\n",
    "\n",
    "# create a surface from the rectangle\n",
    "boundary_rect = rs.AddPlaneSurface(plane, width, height)\n",
    "\n",
    "# Subtracting the pattern from the rectangle\n",
    "# (make sure that \"boundary_diff\" is the only input who is connected to the preview box)\n",
    "boundary_diff = rs. BooleanDifference(boundary_rect, boundary_lines, 0)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
